# Generated by Django 4.1 on 2022-10-27 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('iataCode', models.CharField(max_length=4)),
                ('city', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_date', models.CharField(max_length=32)),
                ('arrival_date', models.CharField(max_length=32)),
                ('airline', models.CharField(max_length=128)),
                ('plane', models.CharField(max_length=128)),
                ('duration', models.CharField(max_length=16)),
                ('price', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='travel.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='travel.airport')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='flights', to='travel.flight'),
        ),
    ]
