# Generated by Django 4.1 on 2022-10-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_airport_city_alter_airport_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='price',
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AlterField(
            model_name='flight',
            name='plane',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
