# Generated by Django 4.1 on 2023-05-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_remove_flight_price_alter_flight_airline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pnr_number',
            field=models.CharField(default=None, max_length=6, null=True, unique=True),
        ),
    ]
