# Generated by Django 4.2.5 on 2024-04-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_booking_pnr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='flight_type',
            field=models.CharField(default='departure', max_length=10),
        ),
    ]
