# Generated by Django 4.2.5 on 2024-04-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_booking_flight_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='flight_type',
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(default='departure', max_length=10),
        ),
    ]
